spring.datasource.url=jdbc:postgresql://joycart.ckx42mi0mccc.us-east-1.rds.amazonaws.com:5432/joycart
spring.datasource.username=joycartadmin
spring.datasource.password=joycartadmin123
spring.jpa.hibernate.ddl-auto=update
server.port=8083
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=mySecretKeyForJoyCartApplicationThatIsLongEnoughForHS256AndShouldBeChangedInProduction
# Jwt Expiration Time in milliseconds (24 hours)
jwt.expiration=86400000

# Security Configuration
security.cors.allowed-origins=http://localhost:3000
security.public-endpoints=/users/register,/users/login,/search/**