spring.datasource.url=jdbc:postgresql://joycart.ckx42mi0mccc.us-east-1.rds.amazonaws.com:5432/joycart
spring.datasource.username=joycartadmin
spring.datasource.password=joycartadmin123
spring.jpa.hibernate.ddl-auto=update
server.port=8083
spring.jpa.show-sql=true